# Run on LastFM
"""
run_lastfm.py — DL model training and inference on Last.fm
================================================
Last.fm is implicit feedback and requires negative sampling.
Additionally, run SASRec (sequential model) to leverage Last.fm's temporal information.

Run:
    python run_lastfm.py

Output:
    predictions/lastfm/neumf.pkl
    predictions/lastfm/two_tower.pkl
    predictions/lastfm/sasrec.pkl
"""

import os
import json
import logging
import pickle

import numpy as np
import torch
from torch.utils.data import DataLoader

import sys
_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
sys.path.insert(0, _ROOT)
sys.path.insert(0, _HERE)

from src.data_loader import load_splits_from_csv, load_metadata
from models.ncf import NeuMF
from models.two_tower import TwoTowerModel
from models.sasrec import SASRec
from datasets import PointwiseDataset, SequenceDataset, build_user_sequences
from trainer import PointwiseTrainer, SASRecTrainer
from tuning import tune_neumf, tune_two_tower, tune_sasrec
from inference import (
    generate_predictions_pointwise,
    generate_predictions_sasrec,
    save_predictions,
)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
logger = logging.getLogger(__name__)

DATASET = "lastfm"
DATA_DIR = os.path.join(_ROOT, "data")
SPLITS_DIR = os.path.join(DATA_DIR, "splits", DATASET)
PRED_DIR = os.path.join(_ROOT, "predictions")
CKPT_DIR = os.path.join(_HERE, "ckpts")
RESULT_DIR = os.path.join(_HERE, "results")

K = 10
SEEDS = [42, 123, 2024]
N_OPTUNA_TRIALS = 25
N_EPOCHS = 30
BATCH_SIZE = 512
NUM_NEG = 4

os.makedirs(CKPT_DIR, exist_ok=True)
os.makedirs(RESULT_DIR, exist_ok=True)
os.makedirs(os.path.join(PRED_DIR, DATASET), exist_ok=True)


def load_data():
    """Load Last.fm data (directly read the CSV generated by A, without relying on the original data files)."""
    logger.info(f"Loading data from {SPLITS_DIR}")
    train, val, test = load_splits_from_csv(SPLITS_DIR)
    meta = load_metadata(SPLITS_DIR)
    logger.info(
        f"Last.fm | n_users={meta['n_users']}, n_items={meta['n_items']} "
        f"| train={len(train)}, val={len(val)}, test={len(test)}"
    )
    return train, val, test, meta


def _negative_sample(data: "pd.DataFrame", n_items: int, num_neg: int,
                     strategy: str, rng: "np.random.RandomState") -> "pd.DataFrame":
    """
    Independent negative sampling function, does not rely on RecommenderDataLoader.
    The logic is completely consistent with A's get_negative_samples().
    """
    import pandas as pd
    all_items = set(range(n_items))
    user_pos_items = data.groupby("user_id")["item_id"].apply(set).to_dict()

    if strategy == "popularity":
        item_counts = data["item_id"].value_counts()
        item_probs = item_counts / item_counts.sum()
        pop_items = item_probs.index.values
        pop_probs = item_probs.values

    neg_records = []
    for _, row in data.iterrows():
        uid = row["user_id"]
        pos_items = user_pos_items.get(uid, set())
        candidates = list(all_items - pos_items)
        if not candidates:
            continue
        actual_neg = min(num_neg, len(candidates))
        if strategy == "uniform":
            sampled = rng.choice(candidates, size=actual_neg, replace=False)
        else:
            cand_set = set(candidates)
            mask = np.array([it in cand_set for it in pop_items])
            f_items = pop_items[mask]
            f_probs = pop_probs[mask]
            if len(f_items) == 0:
                continue
            f_probs = f_probs / f_probs.sum()
            sampled = rng.choice(f_items, size=min(actual_neg, len(f_items)),
                                 replace=False, p=f_probs)
        for neg_item in sampled:
            neg_records.append({"user_id": uid, "item_id": int(neg_item),
                                 "rating": 0.0, "timestamp": row["timestamp"], "label": 0})

    neg_df = pd.DataFrame(neg_records)
    pos_df = data.copy()
    pos_df["label"] = 1
    combined = pd.concat([pos_df, neg_df], ignore_index=True)
    return combined.sample(frac=1, random_state=rng.randint(0, 99999)).reset_index(drop=True)


def get_neg_sampled_data(train, val, n_items: int,
                         num_neg: int = NUM_NEG, seed: int = 42):
    """Generate negative sampled data for train/val, each seed results in different (reflecting sampling sensitivity)."""
    rng = np.random.RandomState(seed)
    train_neg = _negative_sample(train, n_items, num_neg, "uniform", rng)
    val_neg   = _negative_sample(val,   n_items, num_neg, "uniform", rng)
    return train_neg, val_neg


def run_neumf_lastfm(train, val, test, meta, best_params=None):
    n_users, n_items = meta["n_users"], meta["n_items"]

    # Use negative sampled data with seed=42 for hyperparameter tuning
    train_neg_tune, val_neg_tune = get_neg_sampled_data(train, val, n_items, seed=42)

    if best_params is None:
        logger.info("=== NeuMF (LastFM) Hyperparameter Tuning ===")
        best_params = tune_neumf(train_neg_tune, val_neg_tune, n_users, n_items,
                                 n_trials=N_OPTUNA_TRIALS, n_epochs=12)
        with open(os.path.join(RESULT_DIR, "lastfm_neumf_best_params.json"), "w") as f:
            json.dump(best_params, f, indent=2)

    emb_dim = best_params.get("emb_dim", 64)
    n_mlp_layers = best_params.get("n_mlp_layers", 3)
    hidden_0 = best_params.get("hidden_0", 256)
    hidden_dims = [hidden_0 // (2 ** i) for i in range(n_mlp_layers)]
    lr = best_params.get("lr", 1e-3)
    wd = best_params.get("weight_decay", 1e-5)
    batch_size = best_params.get("batch_size", BATCH_SIZE)

    all_predictions = []
    for seed in SEEDS:
        logger.info(f"=== NeuMF (LastFM) Seed={seed} ===")
        torch.manual_seed(seed)
        np.random.seed(seed)

        # Each seed is resampled negatively (to reflect sensitivity).
        train_neg, val_neg = get_neg_sampled_data(train, val, n_items, seed=seed)

        model = NeuMF(n_users, n_items,
                      gmf_emb_dim=emb_dim,
                      mlp_emb_dim=emb_dim,
                      hidden_dims=hidden_dims)

        train_loader = DataLoader(PointwiseDataset(train_neg),
                                  batch_size=batch_size, shuffle=True)
        val_loader = DataLoader(PointwiseDataset(val_neg),
                                batch_size=batch_size)

        trainer = PointwiseTrainer(model, lr=lr, weight_decay=wd)
        history = trainer.fit(train_loader, val_loader,
                              n_epochs=N_EPOCHS, patience=5,
                              ckpt_path=os.path.join(CKPT_DIR, f"lastfm_neumf_seed{seed}.pt"))
        with open(os.path.join(RESULT_DIR, f"lastfm_neumf_history_seed{seed}.json"), "w") as f:
            json.dump(history, f)

        test_user_ids = test["user_id"].unique().tolist()
        preds = generate_predictions_pointwise(model, test_user_ids, n_items, train, K=K)
        all_predictions.append(preds)

    final_preds = all_predictions[-1]
    save_predictions(final_preds, DATASET, "neumf", output_dir=PRED_DIR)
    with open(os.path.join(PRED_DIR, DATASET, "neumf_all_seeds.pkl"), "wb") as f:
        pickle.dump(all_predictions, f)
    logger.info("NeuMF (LastFM) done.")
    return final_preds


def run_two_tower_lastfm(train, val, test, meta, best_params=None):
    n_users, n_items = meta["n_users"], meta["n_items"]

    train_neg_tune, val_neg_tune = get_neg_sampled_data(train, val, n_items, seed=42)

    if best_params is None:
        logger.info("=== TwoTower (LastFM) Hyperparameter Tuning ===")
        best_params = tune_two_tower(train_neg_tune, val_neg_tune, n_users, n_items,
                                     n_trials=N_OPTUNA_TRIALS, n_epochs=12)
        with open(os.path.join(RESULT_DIR, "lastfm_two_tower_best_params.json"), "w") as f:
            json.dump(best_params, f, indent=2)

    emb_dim = best_params.get("emb_dim", 64)
    output_dim = best_params.get("output_dim", 64)
    tower_hidden = best_params.get("tower_hidden", 128)
    lr = best_params.get("lr", 1e-3)
    wd = best_params.get("weight_decay", 1e-5)
    batch_size = best_params.get("batch_size", BATCH_SIZE)
    temperature = best_params.get("temperature", 0.1)

    all_predictions = []
    for seed in SEEDS:
        logger.info(f"=== TwoTower (LastFM) Seed={seed} ===")
        torch.manual_seed(seed)
        np.random.seed(seed)

        train_neg, val_neg = get_neg_sampled_data(train, val, n_items, seed=seed)

        model = TwoTowerModel(n_users, n_items,
                              emb_dim=emb_dim,
                              tower_hidden=[tower_hidden],
                              output_dim=output_dim,
                              temperature=temperature)

        train_loader = DataLoader(PointwiseDataset(train_neg),
                                  batch_size=batch_size, shuffle=True)
        val_loader = DataLoader(PointwiseDataset(val_neg),
                                batch_size=batch_size)

        trainer = PointwiseTrainer(model, lr=lr, weight_decay=wd)
        history = trainer.fit(train_loader, val_loader,
                              n_epochs=N_EPOCHS, patience=5,
                              ckpt_path=os.path.join(CKPT_DIR, f"lastfm_two_tower_seed{seed}.pt"))
        with open(os.path.join(RESULT_DIR, f"lastfm_two_tower_history_seed{seed}.json"), "w") as f:
            json.dump(history, f)

        test_user_ids = test["user_id"].unique().tolist()
        preds = generate_predictions_pointwise(model, test_user_ids, n_items, train, K=K)
        all_predictions.append(preds)

    final_preds = all_predictions[-1]
    save_predictions(final_preds, DATASET, "two_tower", output_dir=PRED_DIR)
    with open(os.path.join(PRED_DIR, DATASET, "two_tower_all_seeds.pkl"), "wb") as f:
        pickle.dump(all_predictions, f)
    logger.info("TwoTower (LastFM) done.")
    return final_preds


def run_sasrec_lastfm(train, val, test, meta, best_params=None):
    """SASRec — Sequential model, only run on Last.fm (with temporal significance)."""
    n_items = meta["n_items"]

    if best_params is None:
        logger.info("=== SASRec (LastFM) Hyperparameter Tuning ===")
        best_params = tune_sasrec(train, val, n_items,
                                  n_trials=N_OPTUNA_TRIALS, n_epochs=15)
        with open(os.path.join(RESULT_DIR, "lastfm_sasrec_best_params.json"), "w") as f:
            json.dump(best_params, f, indent=2)

    emb_dim = best_params.get("emb_dim", 64)
    n_heads = best_params.get("n_heads", 2)
    n_layers = best_params.get("n_layers", 2)
    max_seq_len = best_params.get("max_seq_len", 50)
    dropout = best_params.get("dropout", 0.2)
    lr = best_params.get("lr", 1e-3)
    wd = best_params.get("weight_decay", 1e-5)
    batch_size = best_params.get("batch_size", 256)

    all_predictions = []
    for seed in SEEDS:
        logger.info(f"=== SASRec (LastFM) Seed={seed} ===")
        torch.manual_seed(seed)
        np.random.seed(seed)

        train_dataset = SequenceDataset(train, n_items,
                                        max_seq_len=max_seq_len, seed=seed)
        val_dataset = SequenceDataset(val, n_items,
                                      max_seq_len=max_seq_len, seed=seed)
        train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
        val_loader = DataLoader(val_dataset, batch_size=batch_size)

        model = SASRec(n_items, max_seq_len=max_seq_len,
                       emb_dim=emb_dim, n_heads=n_heads,
                       n_layers=n_layers, dropout=dropout)
        trainer = SASRecTrainer(model, lr=lr, weight_decay=wd)
        history = trainer.fit(train_loader, val_loader,
                              n_epochs=N_EPOCHS, patience=5,
                              ckpt_path=os.path.join(CKPT_DIR, f"lastfm_sasrec_seed{seed}.pt"))
        with open(os.path.join(RESULT_DIR, f"lastfm_sasrec_history_seed{seed}.json"), "w") as f:
            json.dump(history, f)

        # Build user history sequences for inference (full training set)
        user_seqs = build_user_sequences(train, max_seq_len=max_seq_len)
        test_user_ids = test["user_id"].unique().tolist()
        preds = generate_predictions_sasrec(
            model, test_user_ids, user_seqs, n_items, train, K=K
        )
        all_predictions.append(preds)

    final_preds = all_predictions[-1]
    save_predictions(final_preds, DATASET, "sasrec", output_dir=PRED_DIR)
    with open(os.path.join(PRED_DIR, DATASET, "sasrec_all_seeds.pkl"), "wb") as f:
        pickle.dump(all_predictions, f)
    logger.info("SASRec (LastFM) done.")
    return final_preds


if __name__ == "__main__":
    train, val, test, meta = load_data()

    run_neumf_lastfm(train, val, test, meta)
    run_two_tower_lastfm(train, val, test, meta)
    run_sasrec_lastfm(train, val, test, meta)

    logger.info("=== Last.fm Done ===")
    logger.info("Outputs:")
    logger.info(f"  predictions/{DATASET}/neumf.pkl")
    logger.info(f"  predictions/{DATASET}/two_tower.pkl")
    logger.info(f"  predictions/{DATASET}/sasrec.pkl")
    logger.info(f"  predictions/{DATASET}/*_all_seeds.pkl  (D for multi-seed analysis)")
